const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("riverside", {
  platform: process.platform,
  window: {
    minimize: () => ipcRenderer.invoke("window:minimize"),
    toggleMaximize: () => ipcRenderer.invoke("window:toggleMaximize"),
    close: () => ipcRenderer.invoke("window:close"),
    getBounds: () => ipcRenderer.invoke("window:getBounds"),
    getMinSize: () => ipcRenderer.invoke("window:getMinSize"),
    setBounds: (bounds) => ipcRenderer.send("window:setBounds", bounds),
    setCollapsed: (collapsed) => ipcRenderer.invoke("window:setCollapsed", collapsed),
  },
  files: {
    pickImages: () => ipcRenderer.invoke("app:pickImages"),
  },
  forum: {
    getSession: () => ipcRenderer.invoke("forum:getSession"),
    openLogin: () => ipcRenderer.invoke("forum:openLogin"),
    openProfileSettings: () => ipcRenderer.invoke("forum:openProfileSettings"),
    logout: () => ipcRenderer.invoke("forum:logout"),
    listEmojis: () => ipcRenderer.invoke("forum:listEmojis"),
    listDMs: () => ipcRenderer.invoke("forum:listDMs"),
    listChatChannels: () => ipcRenderer.invoke("forum:listChatChannels"),
    getChatMessages: (channelId, opts) => ipcRenderer.invoke("forum:getChatMessages", channelId, opts),
    markChatChannelRead: (channelId, messageId) =>
      ipcRenderer.invoke("forum:markChatChannelRead", { channelId, messageId }),
    sendChatMessage: (channelId, message, uploadIds, replyToMessageId) =>
      ipcRenderer.invoke("forum:sendChatMessage", { channelId, message, uploadIds, replyToMessageId }),
    uploadFile: (filePath, type) => ipcRenderer.invoke("forum:uploadFile", { filePath, type }),
    uploadBytes: (payload) => ipcRenderer.invoke("forum:uploadBytes", payload),
    getMyProfile: () => ipcRenderer.invoke("forum:getMyProfile"),
    updateMyProfile: (payload) => ipcRenderer.invoke("forum:updateMyProfile", payload),
    updateMyAvatar: (filePath) => ipcRenderer.invoke("forum:updateMyAvatar", { filePath }),
    getTopic: (topicId) => ipcRenderer.invoke("forum:getTopic", topicId),
    replyTopic: (topicId, raw, uploadIds, replyToPostNumber) =>
      ipcRenderer.invoke("forum:replyTopic", { topicId, raw, uploadIds, replyToPostNumber }),
    listLatest: (opts) => ipcRenderer.invoke("forum:listLatest", opts),
    listCategoryTopics: (categoryId, slug, page) =>
      ipcRenderer.invoke("forum:listCategoryTopics", { categoryId, slug, page }),
    listUserCreatedTopics: (payload) => ipcRenderer.invoke("forum:listUserCreatedTopics", payload),
    searchUsers: (payload) => ipcRenderer.invoke("forum:searchUsers", payload),
    getUser: (username) => ipcRenderer.invoke("forum:getUser", username),
    ensureDmWith: (payload) => ipcRenderer.invoke("forum:ensureDmWith", payload),
    createTopic: (payload) => ipcRenderer.invoke("forum:createTopic", payload),
    setLikeOnTopic: (topicId, liked) =>
      ipcRenderer.invoke("forum:setLikeOnTopic", { topicId, liked }),
    listNotifications: (opts) => ipcRenderer.invoke("forum:listNotifications", opts),
    markNotificationRead: (payload) => ipcRenderer.invoke("forum:markNotificationRead", payload),
    markAllNotificationsRead: () => ipcRenderer.invoke("forum:markAllNotificationsRead"),
  },
  legacy: {
    getSession: () => ipcRenderer.invoke("legacy:getSession"),
    openLogin: () => ipcRenderer.invoke("legacy:openLogin"),
    logout: () => ipcRenderer.invoke("legacy:logout"),
    listForumTree: () => ipcRenderer.invoke("legacy:listForumTree"),
    listLatest: (payload) => ipcRenderer.invoke("legacy:listLatest", payload),
    listForumThreads: (payload) => ipcRenderer.invoke("legacy:listForumThreads", payload),
    getThread: (payload) => ipcRenderer.invoke("legacy:getThread", payload),
    resolveFindpost: (payload) => ipcRenderer.invoke("legacy:resolveFindpost", payload),
    getNewThreadForm: (payload) => ipcRenderer.invoke("legacy:getNewThreadForm", payload),
    createThread: (payload) => ipcRenderer.invoke("legacy:createThread", payload),
    getReplyForm: (payload) => ipcRenderer.invoke("legacy:getReplyForm", payload),
    replyThread: (payload) => ipcRenderer.invoke("legacy:replyThread", payload),
    listPmThreads: () => ipcRenderer.invoke("legacy:listPmThreads"),
    getPmMessages: (payload) => ipcRenderer.invoke("legacy:getPmMessages", payload),
    sendPmMessage: (payload) => ipcRenderer.invoke("legacy:sendPmMessage", payload),
    searchUsers: (payload) => ipcRenderer.invoke("legacy:searchUsers", payload),
    getUser: (payload) => ipcRenderer.invoke("legacy:getUser", payload),
    listUserCreatedTopics: (payload) => ipcRenderer.invoke("legacy:listUserCreatedTopics", payload),
    listNotifications: (payload) => ipcRenderer.invoke("legacy:listNotifications", payload),
    openExternal: (url) => ipcRenderer.invoke("legacy:openExternal", url),
  },
  openExternal: (url) => ipcRenderer.invoke("app:openExternal", url),
});
